### ISSUE TITLE
scikit-hep particle module

### ISSUE THREAD

**Issue by HDembinski** [afedynitch/ParticleDataTool#5]
Hi Anatoli,

I joined the [Scikit-HEP project](https://github.com/scikit-hep/), a group of high-profile people from CERN who aim to provide an alternative science stack for HEP based on Python, which does not need ROOT as a dependency. The iminuit repository was moved to scikit-hep and pyhepmc_ng will also move there. Particularly impressive is *uproot*, a pure-Python implementation of a reader for ROOT files, which provides tree data directly as a form of special numpy arrays (so-called jagged arrays, invented for this purpose).

They are currently building a module called `particle`, which provides most of the information in this module, minus the translation service from other ID systems to PDGID. I think it would be great if you had a look or even join the development of `particle`.

**Comment by eduardo-rodrigues** [comment]
BTW, we've made major improvements/extensions to the [Particle](https://github.com/scikit-hep/particle) package and have been in touch with the PDG. There's interest from their side too … It would be great if we could join forces …

**Comment by afedynitch** [comment]
Hi Eduardo,

thanks for your interest in the package. It's a very cool effort to create a solid ecosystem for particle physics data analysis in Python.

I'm interested in joining forces since the overlap is definitely high. As Hans pointed out, one of the main features/purposes of particletools are the translations between different particle code systems. Instead of the PDG tables, I readout the Pythia8 XML what mainly happened historical reasons. One requirement for my codes are fast initialization times of the conversion classes and fast lookup of particle properties. 

Hans has some ideas on the implementation scenarios on [the scihep-particle issues](https://github.com/scikit-hep/particle/issues/25)? I'm fine with whatever fits nicely in the scihep style and as long as initialization and lookups stay fast. Any proposal how to proceed from here?

**Comment by eduardo-rodrigues** [comment]
Thanks a lot for the thumbs up!

Excellent news! Let's then try and come up with a proposal. I've got some ideas based on the "issue" you refer above. I will get back to you next week as I'm rather busy until Monday 23th, OK? I will suggest what we might want as an API for the conversions and all that, and we go from there, iterating.

Thanks again.

**Comment by afedynitch** [comment]
Thanks, sounds good! 
I'm busy as well, at least until Tuesday 27th May. Let's continue after that date...

**Comment by eduardo-rodrigues** [comment]
From now on I will continue the discussion and proposal in https://github.com/scikit-hep/particle/issues/25 as that's for the Particle package, OK? Feel free to close this. Talk to you soon!

**Comment by afedynitch** [comment]
Moved to [https://github.com/scikit-hep/particle/issues/25](https://github.com/scikit-hep/particle/issues/25)
